### PR TITLE
fix 'make tools-learn-sha' on macOS

### PR DESCRIPTION
**Pull request by SgtCoDFish**
Also updates shasums for darwin; I confimed manually that these are correct:

```console
$ curl -LO https://go.dev/dl/go1.22.3.darwin-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    76  100    76    0     0    253      0 --:--:-- --:--:-- --:--:--   252
100 64.1M  100 64.1M    0     0  26.5M      0  0:00:02  0:00:02 --:--:-- 35.2M
$ sha256sum go1.22.3.darwin-arm64.tar.gz
02abeab3f4b8981232237ebd88f0a9bad933bc9621791cd7720a9ca29eacbe9d  go1.22.3.darwin-arm64.tar.gz
$ sha256sum go1.22.3.darwin-amd64.tar.gz
sha256sum: go1.22.3.darwin-amd64.tar.gz: No such file or directory
$ curl -LO https://go.dev/dl/go1.22.3.darwin-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    76  100    76    0     0    295      0 --:--:-- --:--:-- --:--:--   294
100 67.0M  100 67.0M    0     0  24.9M      0  0:00:02  0:00:02 --:--:-- 32.9M
$ sha256sum go1.22.3.darwin-amd64.tar.gz
610e48c1df4d2f852de8bc2e7fd2dc1521aac216f0c0026625db12f67f192024  go1.22.3.darwin-amd64.tar.gz
```

### CODE REVIEW

**Comment by maelvls** [comment]
Hey. I wasn't sure whether I had to open an issue, so I will post this here. 

On macOS, when running:

```
make learn-tools-shas
```

the command fails with:

```
bash: line 1: /var/tmp/.../_bin/tools/go: cannot execute binary file: Exec format error
```

That's because the following is being run:

```
./scripts/learn_tools_shas.sh tools vendor-go
```

which in turn is calling:

```
  make \
   HOST_OS=linux \
   HOST_ARCH=arm64 \
    -f ./learn_tools_shas.helper.mk tools vendor-go
```

Since the `vendor-go` target is used, the wrong Go binary is used, leading to the Exec format error.

How did you work around this problem?

**Comment by SgtCoDFish** [comment]
I'd open an issue and ping Tim, I don't remember seeing anything like that and I'm not working tomorrow to be able to debug!

**Comment by maelvls** [comment]
Thanks Ash!

I've worked a bit with Tim on that. We found that if we put darwin/arm64 first in the list, it works:

```diff
diff --git a/scripts/learn_tools_shas.sh b/scripts/learn_tools_shas.sh
index 7f6bd5a..4eabb19 100755
--- a/scripts/learn_tools_shas.sh
+++ b/scripts/learn_tools_shas.sh
@@ -46,7 +46,7 @@ learn_file="learn_tools_file"
 echo -n "" > "${learn_file}"
 
 # Loop over each OS and ARCH combination and download the tools
-for os_arch in linux/amd64 linux/arm64 darwin/amd64 darwin/arm64; do
+for os_arch in darwin/arm64 linux/amd64 linux/arm64 darwin/amd64; do
```

**Pull request merged**
