### PR TITLE
Helm chart OCI publish

### PR DESCRIPTION
**Pull request by inteon**
Adds `helm-chart-oci-push` target and enforce v-prefixed Helm chart versions as primary version.
Additionally, the `helm-chart-oci-push` target now publishes a non-v-prefixed version which improves Helm compatibility and provides backwards compatibility for some projects that only published a non-v-prefixed version before.

### CODE REVIEW

**Comment by erikgb** [comment]
/lgtm

But make is non-trivial. 😉

**Review by wallrj — COMMENTED** [review]
Suggest updating the [test-project](https://github.com/cert-manager/makefile-modules/tree/main/tests/e2e-projects/test-project) and adding some notes about these new targets to a README file in https://github.com/cert-manager/makefile-modules/tree/main/modules/helm

Explain the interplay between these new OCI related targets and those in the oci-build and oci-publish modules.

**Pull request merged**
