### PR TITLE
Update kind.mk

### PR DESCRIPTION
**Pull request by jabdoa2**
Commit change from https://github.com/cert-manager/trust-manager/pull/387 in the correct location

### CODE REVIEW

**Comment by inteon** [comment]
I updated the fix based on how I think this target was originally designed.
It looks like `kind-cluster` was not meant to be used as a dependency by other targets, instead they should have depended on `$(kind_kubeconfig)`.
This PR replaces `kind-cluster` with a simple "depend on `$(kind_kubeconfig)`" target and renames the old `kind-cluster` target to `kind-cluster-load`.

PTAL and let me know what you think.

**Comment by jabdoa2** [comment]
> I updated the fix based on how I think this target was originally designed. It looks like `kind-cluster` was not meant to be used as a dependency by other targets, instead they should have depended on `$(kind_kubeconfig)`. This PR replaces `kind-cluster` with a simple "depend on `$(kind_kubeconfig)`" target and renames the old `kind-cluster` target to `kind-cluster-load`.
> 
> PTAL and let me know what you think.

Not sure. Even in that case it should not silently overwrite my kubectl config and purge all my cluster configs. At least ask with a huge warning. Took me a few hour to get all my clusters configured again. Ideally it would merge into an existing config or we could use a separate config since we set the environment variable anyway.

**Comment by inteon** [comment]
> > I updated the fix based on how I think this target was originally designed. It looks like `kind-cluster` was not meant to be used as a dependency by other targets, instead they should have depended on `$(kind_kubeconfig)`. This PR replaces `kind-cluster` with a simple "depend on `$(kind_kubeconfig)`" target and renames the old `kind-cluster` target to `kind-cluster-load`.
> > PTAL and let me know what you think.
> 
> Not sure. Even in that case it should not silently overwrite my kubectl config and purge all my cluster configs. At least ask with a huge warning. Took me a few hour to get all my clusters configured again. Ideally it would merge into an existing config or we could use a separate config since we set the environment variable anyway.

It is surprising that the kubectl config is purged, normally the command should merge the kubeconfig into your global kubeconfig. It seems like there is another bug here that we should fix.

**Review by inteon — COMMENTED** [review]
Let's start with this change and gather some feedback.
/approve
/lgtm

**Pull request merged**
